### ISSUE TITLE
Error building service model

### ISSUE THREAD

**Issue by vmgeert** [Fedict/eid-trust-service#6]
Downloading: http://repo.maven.apache.org/maven2/be/fedict/eid-applet/eid-applet-bom/2.0.1.FEDICT/eid-applet-bom-2.0.1.FEDICT.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project be.fedict:eid-trust-service:1.2.1.FEDICT-SNAPSHOT (/home/geert/Work/Develop/eid-trust-service/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not transfer artifact be.fedict.eid-applet:eid-applet-bom:pom:2.0.1.FEDICT from/to eid-maven-repo (https://maven.eid.belgium.be/): hostname in certificate didn't match: <maven.eid.belgium.be> != <dist.eid.belgium.be> OR <dist.eid.belgium.be> @ line 201, column 16 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by yoe** [comment]
This is because you're using a client (like Java 6) which does not support SNI:

https://www.ssllabs.com/ssltest/analyze.html?d=maven.eid.belgium.be

shows that the correct certificate is available, but only if you use SNI, otherwise the certificate for the default virtual host (dist.eid.belgium.be) is chosen. To get that, you'll need to use Java 7 or above.

This can't be fixed server side, it needs to be fixed client side, so closing the ticket.
